//common
export const WAITING_INDICATOR = 'WAITING_INDICATOR';

export const FAIL = '_FAIL';
export const SUCCESS = '_SUCCESS';

export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REDUX_STORAGE_LOAD = 'REDUX_STORAGE_LOAD';

//login logout register
export const LOGIN_HTTP = 'LOGIN_HTTP';
export const LOGOUT_HTTP = 'LOGOUT_HTTP';
export const REQUEST_SMS_CODE_HTTP = 'REQUEST_SMS_CODE_HTTP';
export const REGISTER_HTTP = 'REGISTER_HTTP';

//user
export const USER_INFO_HTTP = 'USER_INFO_HTTP';
export const USER_ORDER_HTTP = 'USER_ORDER_HTTP';
export const USER_COURSE_HTTP = 'USER_COURSE_HTTP';

//hospital
export const HOSTPIAL_SEARCH = 'HOSPITAL_SEARCH';
export const DEPARTMENT_LIST_HTTP = 'DEPARTMENT_LIST_HTTP';

//notification
export const QUERY_NOTIFICATION = 'QUERY_NOTIFICATION';
export const QUERY_NOTIFICATION_DETAIL_HTTP = 'QUERY_NOTIFICATION_DETAIL_HTTP';

//study
export const QUERY_STUDY_COURSES = 'QUERY_STUDY_COURSES';
export const QUERY_STUDY_COURSES_DETAIL_HTTP = 'QUERY_STUDY_COURSES_DETAIL_HTTP';

//order
export const QUERY_ORDERS = 'QUERY_ORDERS';