//common
export const WAITING_INDICATOR = 'WAITING_INDICATOR';

export const FAIL = '_FAIL';
export const SUCCESS = '_SUCCESS';
export const SET_NAVIGATOR = 'SET_NAVIGATOR';

export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REDUX_STORAGE_LOAD = 'REDUX_STORAGE_LOAD';

//login logout register
export const LOGIN_HTTP = 'LOGIN_HTTP';
export const LOGOUT_HTTP = 'LOGOUT_HTTP';
export const REQUEST_SMS_CODE_HTTP = 'REQUEST_SMS_CODE_HTTP';
export const REGISTER_HTTP = 'REGISTER_HTTP';
export const FORGET_PASSWORD_HTTP = 'FORGET_PASSWORD_HTTP';

//user
export const USER_INFO_HTTP = 'USER_INFO_HTTP';
export const UPDATE_USER_INFO_HTTP = 'UPDATE_USER_INFO_HTTP';
export const USER_ORDER_HTTP = 'USER_ORDER_HTTP';
export const USER_ORDERS = 'USER_ORDERS';
export const USER_COURSE_HTTP = 'USER_COURSE_HTTP';
export const SEND_FEEDBACK_HTTP = 'SEND_FEEDBACK_HTTP';
export const UPDATE_PASSWORD_HTTP = 'UPDATE_PASSWORD_HTTP';

//wallet
export const QUERY_WALLET_HTTP = 'QUERY_WALLET_HTTP';
export const WITHDRAW_HTTP = 'WITHDRAW_HTTP';

//hospital
export const HOSTPIAL_SEARCH = 'HOSPITAL_SEARCH';
export const DEPARTMENT_LIST_HTTP = 'DEPARTMENT_LIST_HTTP';

//notification
export const QUERY_NOTIFICATION = 'QUERY_NOTIFICATION';
export const QUERY_NOTIFICATION_LIST_HTTP = 'QUERY_NOTIFICATION_LIST_HTTP';
export const QUERY_NOTIFICATION_DETAIL_HTTP = 'QUERY_NOTIFICATION_DETAIL_HTTP';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';

//study
export const QUERY_STUDY_COURSES = 'QUERY_STUDY_COURSES';
export const QUERY_STUDY_COURSE_LIST_HTTP = 'QUERY_STUDY_COURSE_LIST_HTTP';
export const QUERY_STUDY_COURSES_DETAIL_HTTP = 'QUERY_STUDY_COURSES_DETAIL_HTTP';
export const READ_STUDY_COURSE = 'READ_STUDY_COURSE';

//order
export const QUERY_ORDERS = 'QUERY_ORDERS';
export const QUERY_ORDER_LIST_HTTP = 'QUERY_ORDER_LIST_HTTP';
export const QUERY_ORDER_HTTP = 'QUERY_ORDER_HTTP';
export const FETCH_ORDER_HTTP = 'FETCH_ORDER_HTTP';
export const CANCEL_ORDER_HTTP = 'CANCEL_ORDER_HTTP';

//visit
export const GET_VISIT_ITEMS_HTTP = 'GET_VISIT_ITEMS_HTTP';
export const ADD_VISIT_HTTP = 'ADD_VISIT_HTTP';
export const SET_PATIENT_SIGNATURE_HTTP = 'SET_PATIENT_SIGNATURE_HTTP';
export const SET_NURSE_SIGNATURE_HTTP = 'SET_NURSE_SIGNATURE_HTTP';
export const REQUEST_UPLOAD_IMAGE_WAITING_HTTP = 'REQUEST_UPLOAD_IMAGE_WAITING_HTTP';

//patient
export const QUERY_INTERNAL_PATIENTS = 'QUERY_INTERNAL_PATIENTS';
export const QUERY_EXTERNAL_PATIENTS = 'QUERY_EXTERNAL_PATIENTS';
export const QUERY_INTERNAL_PATIENTS_LIST_HTTP = 'QUERY_INTERNAL_PATIENTS_LIST_HTTP';
export const QUERY_EXTERNAL_PATIENTS_LIST_HTTP = 'QUERY_EXTERNAL_PATIENTS_LIST_HTTP';
export const QUERY_PATIENT_VISIT_LIST_HTTP = 'QUERY_PATIENT_VISIT_LIST_HTTP';
export const QUERY_NURSE_CASE_BOOKLIST_HTTP = 'QUERY_NURSE_CASE_BOOKLIST_HTTP';
export const QUERY_NURSE_CASE_BOOK_DETAIL_HTTP = 'QUERY_NURSE_CASE_BOOK_DETAIL_HTTP';
export const CREATE_NEW_CASE_BOOK_HTTP = 'CREATE_NEW_CASE_BOOK_HTTP';
export const UPDATE_CASEBOOK_HTTP = 'UPDATE_CASEBOOK_HTTP';
export const CREATE_CASE_RECORD_HTTP = 'CREATE_CASE_RECORD_HTTP';
export const UPDATE_CASE_RECORD_HTTP = 'UPDATE_CASE_RECORD_HTTP';
export const CLEAR_NURSE_CASEBOOK_LIST = 'CLEAR_NURSE_CASEBOOK_LIST';
export const CLEAR_CASEBOOK = 'CLEAR_CASEBOOK';
export const QUERY_VISIT_LIST_HTTP = 'QUERY_VISIT_LIST_HTTP';

//follow up
export const QUERY_FOLLOW_UP_UNREAD_LIST_HTTP = 'QUERY_FOLLOW_UP_UNREAD_LIST_HTTP';
export const QUERY_FOLLOW_UP_READ_LIST_HTTP = 'QUERY_FOLLOW_UP_READ_LIST_HTTP';
export const CLEAR_FOLLOW_UP_LIST = 'CLEAR_FOLLOW_UP_LIST';
export const QUERY_TEMPLATE_LIST_HTTP = 'QUERY_TEMPLATE_LIST_HTTP';
export const QUERY_TEMPLATE_CATEGORY_ITEMS_HTTP = 'QUERY_TEMPLATE_CATEGORY_ITEMS_HTTP';
export const QUERY_TEMPLATE_DETAIL_HTTP = 'QUERY_TEMPLATE_DETAIL_HTTP';
export const CLEAR_TEMPLATE_DETAIL = 'CLEAR_TEMPLATE_DETAIL';
export const CLEAR_TEMPLATE_CATEGORY_ITEMS = 'CLEAR_TEMPLATE_CATEGORY_ITEMS';
export const QUERY_FOLLOW_UP_PATIENT_LIST_HTTP = 'QUERY_FOLLOW_UP_PATIENT_LIST_HTTP';
export const SEND_TEMPLATE_HTTP = 'SEND_TEMPLATE_HTTP';
export const QUERY_QUESTION_LIST_HTTP = 'QUERY_QUESTION_LIST_HTTP';
export const SEND_QUESTIONAIRE_HTTP = 'SEND_QUESTIONAIRE_HTTP';
export const SEND_FOLLOW_UP_HTTP = 'SEND_FOLLOW_UP_HTTP';