//common
export const WAITING_INDICATOR = 'WAITING_INDICATOR';

export const FAIL = '_FAIL';
export const SUCCESS = '_SUCCESS';
export const SET_NAVIGATOR = 'SET_NAVIGATOR';

export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REDUX_STORAGE_LOAD = 'REDUX_STORAGE_LOAD';

//login logout register
export const LOGIN_HTTP = 'LOGIN_HTTP';
export const LOGOUT_HTTP = 'LOGOUT_HTTP';
export const REQUEST_SMS_CODE_HTTP = 'REQUEST_SMS_CODE_HTTP';
export const REGISTER_HTTP = 'REGISTER_HTTP';
export const FORGET_PASSWORD_HTTP = 'FORGET_PASSWORD_HTTP';

//user
export const USER_INFO_HTTP = 'USER_INFO_HTTP';
export const USER_ORDER_HTTP = 'USER_ORDER_HTTP';
export const USER_ORDERS = 'USER_ORDERS';
export const USER_COURSE_HTTP = 'USER_COURSE_HTTP';
export const SEND_FEEDBACK_HTTP = 'SEND_FEEDBACK_HTTP';
export const UPDATE_PASSWORD_HTTP = 'UPDATE_PASSWORD_HTTP';

//wallet
export const QUERY_WALLET_HTTP = 'QUERY_WALLET_HTTP';
export const WITHDRAW_HTTP = 'WITHDRAW_HTTP';

//hospital
export const HOSTPIAL_SEARCH = 'HOSPITAL_SEARCH';
export const DEPARTMENT_LIST_HTTP = 'DEPARTMENT_LIST_HTTP';

//notification
export const QUERY_NOTIFICATION = 'QUERY_NOTIFICATION';
export const QUERY_NOTIFICATION_LIST_HTTP = 'QUERY_NOTIFICATION_LIST_HTTP';
export const QUERY_NOTIFICATION_DETAIL_HTTP = 'QUERY_NOTIFICATION_DETAIL_HTTP';

//study
export const QUERY_STUDY_COURSES = 'QUERY_STUDY_COURSES';
export const QUERY_STUDY_COURSE_LIST_HTTP = 'QUERY_STUDY_COURSE_LIST_HTTP';
export const QUERY_STUDY_COURSES_DETAIL_HTTP = 'QUERY_STUDY_COURSES_DETAIL_HTTP';

//order
export const QUERY_ORDERS = 'QUERY_ORDERS';
export const QUERY_ORDER_LIST_HTTP = 'QUERY_ORDER_LIST_HTTP';
export const QUERY_ORDER_HTTP = 'QUERY_ORDER_HTTP';
export const FETCH_ORDER_HTTP = 'FETCH_ORDER_HTTP';
export const CANCEL_ORDER_HTTP = 'CANCEL_ORDER_HTTP';

//visit
export const GET_VISIT_ITEMS_HTTP = 'GET_VISIT_ITEMS_HTTP';
export const ADD_VISIT_HTTP = 'ADD_VISIT_HTTP';
export const SET_PATIENT_SIGNATURE_HTTP = 'SET_PATIENT_SIGNATURE_HTTP';
export const SET_NURSE_SIGNATURE_HTTP = 'SET_NURSE_SIGNATURE_HTTP';
export const REQUEST_UPLOAD_IMAGE_WAITING_HTTP = 'REQUEST_UPLOAD_IMAGE_WAITING_HTTP';